/* eslint-disable */
export const district = [{
  "id": 123123,
  "areaName": "只有一级",
}, {
  "id": 340000,
  "areaName": "安徽省",
  "subArea": [{
    "id": 341500,
    "areaName": "六安市",
    "subArea": [{
      "id": 341522,
      "areaName": "霍邱县",
      "subArea": []
    }, {
      "id": 341525,
      "areaName": "霍山县",
      "subArea": []
    }, {
      "id": 341502,
      "areaName": "金安区",
      "subArea": []
    }, {
      "id": 341524,
      "areaName": "金寨县",
      "subArea": []
    }, {
      "id": 341526,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 341521,
      "areaName": "寿县",
      "subArea": []
    }, {
      "id": 341523,
      "areaName": "舒城县",
      "subArea": []
    }, {
      "id": 341503,
      "areaName": "裕安区",
      "subArea": []
    }]
  }, {
    "id": 340500,
    "areaName": "马鞍山市",
    "subArea": [{
      "id": 340506,
      "areaName": "博望区",
      "subArea": []
    }]
  }, {
    "id": 341800,
    "areaName": "宣城市",
    "subArea": [{
      "id": 341822,
      "areaName": "广德县",
      "subArea": []
    }, {
      "id": 341824,
      "areaName": "绩溪县",
      "subArea": []
    }, {
      "id": 341825,
      "areaName": "旌德县",
      "subArea": []
    }]
  }]
}, {
  "id": 820000,
  "areaName": "澳门特别行政区",
  "subArea": [{
    "id": 820100,
    "areaName": "澳门半岛",
    "subArea": []
  }, {
    "id": 820200,
    "areaName": "离岛",
    "subArea": []
  }]
}, {
  "id": 110000,
  "areaName": "北京",
  "subArea": [{
    "id": 110100,
    "areaName": "北京市",
    "subArea": [{
      "id": 110114,
      "areaName": "昌平区",
      "subArea": []
    }, {
      "id": 110105,
      "areaName": "朝阳区",
      "subArea": []
    }, {
      "id": 110103,
      "areaName": "崇文区",
      "subArea": []
    }, {
      "id": 110115,
      "areaName": "大兴区",
      "subArea": []
    }, {
      "id": 110101,
      "areaName": "东城区",
      "subArea": []
    }, {
      "id": 110111,
      "areaName": "房山区",
      "subArea": []
    }, {
      "id": 110106,
      "areaName": "丰台区",
      "subArea": []
    }, {
      "id": 110108,
      "areaName": "海淀区",
      "subArea": []
    }, {
      "id": 110116,
      "areaName": "怀柔区",
      "subArea": []
    }, {
      "id": 110109,
      "areaName": "门头沟区",
      "subArea": []
    }, {
      "id": 110228,
      "areaName": "密云县",
      "subArea": []
    }, {
      "id": 110117,
      "areaName": "平谷区",
      "subArea": []
    }, {
      "id": 110230,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 110107,
      "areaName": "石景山区",
      "subArea": []
    }, {
      "id": 110113,
      "areaName": "顺义区",
      "subArea": []
    }, {
      "id": 110112,
      "areaName": "通州区",
      "subArea": []
    }, {
      "id": 110102,
      "areaName": "西城区",
      "subArea": []
    }, {
      "id": 110104,
      "areaName": "宣武区",
      "subArea": []
    }, {
      "id": 110229,
      "areaName": "延庆县",
      "subArea": []
    }]
  }]
}, {
  "id": 450000,
  "areaName": "广西壮族自治区",
  "subArea": [{
    "id": 450500,
    "areaName": "北海市",
    "subArea": [{
      "id": 450502,
      "areaName": "海城区",
      "subArea": []
    }, {
      "id": 450521,
      "areaName": "合浦县",
      "subArea": []
    }, {
      "id": 450522,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 450512,
      "areaName": "铁山港区",
      "subArea": []
    }, {
      "id": 450503,
      "areaName": "银海区",
      "subArea": []
    }]
  }, {
    "id": 451000,
    "areaName": "百色市",
    "subArea": [{
      "id": 451024,
      "areaName": "德保县",
      "subArea": []
    }, {
      "id": 451025,
      "areaName": "靖西县",
      "subArea": []
    }, {
      "id": 451028,
      "areaName": "乐业县",
      "subArea": []
    }, {
      "id": 451027,
      "areaName": "凌云县",
      "subArea": []
    }, {
      "id": 451031,
      "areaName": "隆林各族自治县",
      "subArea": []
    }, {
      "id": 451026,
      "areaName": "那坡县",
      "subArea": []
    }, {
      "id": 451023,
      "areaName": "平果县",
      "subArea": []
    }, {
      "id": 451032,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 451022,
      "areaName": "田东县",
      "subArea": []
    }, {
      "id": 451029,
      "areaName": "田林县",
      "subArea": []
    }, {
      "id": 451021,
      "areaName": "田阳县",
      "subArea": []
    }, {
      "id": 451030,
      "areaName": "西林县",
      "subArea": []
    }, {
      "id": 451002,
      "areaName": "右江区",
      "subArea": []
    }]
  }, {
    "id": 451400,
    "areaName": "崇左市",
    "subArea": [{
      "id": 451424,
      "areaName": "大新县",
      "subArea": []
    }, {
      "id": 451421,
      "areaName": "扶绥县",
      "subArea": []
    }, {
      "id": 451402,
      "areaName": "江州区",
      "subArea": []
    }, {
      "id": 451423,
      "areaName": "龙州县",
      "subArea": []
    }, {
      "id": 451422,
      "areaName": "宁明县",
      "subArea": []
    }, {
      "id": 451481,
      "areaName": "凭祥市",
      "subArea": []
    }, {
      "id": 451482,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 451425,
      "areaName": "天等县",
      "subArea": []
    }]
  }, {
    "id": 450600,
    "areaName": "防城港市",
    "subArea": [{
      "id": 450681,
      "areaName": "东兴市",
      "subArea": []
    }, {
      "id": 450603,
      "areaName": "防城区",
      "subArea": []
    }, {
      "id": 450602,
      "areaName": "港口区",
      "subArea": []
    }, {
      "id": 450682,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 450621,
      "areaName": "上思县",
      "subArea": []
    }]
  }, {
    "id": 450800,
    "areaName": "贵港市",
    "subArea": [{
      "id": 450802,
      "areaName": "港北区",
      "subArea": []
    }, {
      "id": 450803,
      "areaName": "港南区",
      "subArea": []
    }, {
      "id": 450881,
      "areaName": "桂平市",
      "subArea": []
    }, {
      "id": 450821,
      "areaName": "平南县",
      "subArea": []
    }, {
      "id": 450882,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 450804,
      "areaName": "覃塘区",
      "subArea": []
    }]
  }, {
    "id": 450300,
    "areaName": "桂林市",
    "subArea": [{
      "id": 450303,
      "areaName": "叠彩区",
      "subArea": []
    }, {
      "id": 450332,
      "areaName": "恭城瑶族自治县",
      "subArea": []
    }, {
      "id": 450327,
      "areaName": "灌阳县",
      "subArea": []
    }, {
      "id": 450331,
      "areaName": "荔浦县",
      "subArea": []
    }, {
      "id": 450322,
      "areaName": "临桂区",
      "subArea": []
    }, {
      "id": 450323,
      "areaName": "灵川县",
      "subArea": []
    }, {
      "id": 450328,
      "areaName": "龙胜各族自治县",
      "subArea": []
    }, {
      "id": 450330,
      "areaName": "平乐县",
      "subArea": []
    }, {
      "id": 450333,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 450305,
      "areaName": "七星区",
      "subArea": []
    }, {
      "id": 450324,
      "areaName": "全州县",
      "subArea": []
    }, {
      "id": 450304,
      "areaName": "象山区",
      "subArea": []
    }, {
      "id": 450325,
      "areaName": "兴安县",
      "subArea": []
    }, {
      "id": 450302,
      "areaName": "秀峰区",
      "subArea": []
    }, {
      "id": 450311,
      "areaName": "雁山区",
      "subArea": []
    }, {
      "id": 450321,
      "areaName": "阳朔县",
      "subArea": []
    }, {
      "id": 450326,
      "areaName": "永福县",
      "subArea": []
    }, {
      "id": 450329,
      "areaName": "资源县",
      "subArea": []
    }]
  }, {
    "id": 451200,
    "areaName": "河池市",
    "subArea": [{
      "id": 451227,
      "areaName": "巴马瑶族自治县",
      "subArea": []
    }, {
      "id": 451229,
      "areaName": "大化瑶族自治县",
      "subArea": []
    }, {
      "id": 451224,
      "areaName": "东兰县",
      "subArea": []
    }, {
      "id": 451228,
      "areaName": "都安瑶族自治县",
      "subArea": []
    }, {
      "id": 451223,
      "areaName": "凤山县",
      "subArea": []
    }, {
      "id": 451226,
      "areaName": "环江毛南族自治县",
      "subArea": []
    }, {
      "id": 451202,
      "areaName": "金城江区",
      "subArea": []
    }, {
      "id": 451225,
      "areaName": "罗城仫佬族自治县",
      "subArea": []
    }, {
      "id": 451221,
      "areaName": "南丹县",
      "subArea": []
    }, {
      "id": 451282,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 451222,
      "areaName": "天峨县",
      "subArea": []
    }, {
      "id": 451281,
      "areaName": "宜州市",
      "subArea": []
    }]
  }, {
    "id": 451100,
    "areaName": "贺州市",
    "subArea": [{
      "id": 451102,
      "areaName": "八步区",
      "subArea": []
    }, {
      "id": 451123,
      "areaName": "富川瑶族自治县",
      "subArea": []
    }, {
      "id": 451119,
      "areaName": "平桂管理区",
      "subArea": []
    }, {
      "id": 451124,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 451121,
      "areaName": "昭平县",
      "subArea": []
    }, {
      "id": 451122,
      "areaName": "钟山县",
      "subArea": []
    }]
  }, {
    "id": 451300,
    "areaName": "来宾市",
    "subArea": [{
      "id": 451381,
      "areaName": "合山市",
      "subArea": []
    }, {
      "id": 451324,
      "areaName": "金秀瑶族自治县",
      "subArea": []
    }, {
      "id": 451382,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 451323,
      "areaName": "武宣县",
      "subArea": []
    }, {
      "id": 451322,
      "areaName": "象州县",
      "subArea": []
    }, {
      "id": 451321,
      "areaName": "忻城县",
      "subArea": []
    }, {
      "id": 451302,
      "areaName": "兴宾区",
      "subArea": []
    }]
  }, {
    "id": 450200,
    "areaName": "柳州市",
    "subArea": [{
      "id": 450202,
      "areaName": "城中区",
      "subArea": []
    }, {
      "id": 450205,
      "areaName": "柳北区",
      "subArea": []
    }, {
      "id": 450222,
      "areaName": "柳城县",
      "subArea": []
    }, {
      "id": 450221,
      "areaName": "柳江县",
      "subArea": []
    }, {
      "id": 450204,
      "areaName": "柳南区",
      "subArea": []
    }, {
      "id": 450223,
      "areaName": "鹿寨县",
      "subArea": []
    }, {
      "id": 450227,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 450224,
      "areaName": "融安县",
      "subArea": []
    }, {
      "id": 450225,
      "areaName": "融水苗族自治县",
      "subArea": []
    }, {
      "id": 450226,
      "areaName": "三江侗族自治县",
      "subArea": []
    }, {
      "id": 450203,
      "areaName": "鱼峰区",
      "subArea": []
    }]
  }, {
    "id": 450100,
    "areaName": "南宁市",
    "subArea": [{
      "id": 450126,
      "areaName": "宾阳县",
      "subArea": []
    }, {
      "id": 450127,
      "areaName": "横县",
      "subArea": []
    }, {
      "id": 450105,
      "areaName": "江南区",
      "subArea": []
    }, {
      "id": 450108,
      "areaName": "良庆区",
      "subArea": []
    }, {
      "id": 450123,
      "areaName": "隆安县",
      "subArea": []
    }, {
      "id": 450124,
      "areaName": "马山县",
      "subArea": []
    }, {
      "id": 450128,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 450103,
      "areaName": "青秀区",
      "subArea": []
    }, {
      "id": 450125,
      "areaName": "上林县",
      "subArea": []
    }, {
      "id": 450122,
      "areaName": "武鸣区",
      "subArea": []
    }, {
      "id": 450107,
      "areaName": "西乡塘区",
      "subArea": []
    }, {
      "id": 450102,
      "areaName": "兴宁区",
      "subArea": []
    }, {
      "id": 450109,
      "areaName": "邕宁区",
      "subArea": []
    }]
  }, {
    "id": 450700,
    "areaName": "钦州市",
    "subArea": [{
      "id": 450721,
      "areaName": "灵山县",
      "subArea": []
    }, {
      "id": 450722,
      "areaName": "浦北县",
      "subArea": []
    }, {
      "id": 450723,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 450703,
      "areaName": "钦北区",
      "subArea": []
    }, {
      "id": 450702,
      "areaName": "钦南区",
      "subArea": []
    }]
  }, {
    "id": 450400,
    "areaName": "梧州市",
    "subArea": [{
      "id": 450421,
      "areaName": "苍梧县",
      "subArea": []
    }, {
      "id": 450481,
      "areaName": "岑溪市",
      "subArea": []
    }, {
      "id": 450405,
      "areaName": "长洲区",
      "subArea": []
    }, {
      "id": 450404,
      "areaName": "蝶山区",
      "subArea": []
    }, {
      "id": 450406,
      "areaName": "龙圩区",
      "subArea": []
    }, {
      "id": 450423,
      "areaName": "蒙山县",
      "subArea": []
    }, {
      "id": 450482,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 450422,
      "areaName": "藤县",
      "subArea": []
    }, {
      "id": 450403,
      "areaName": "万秀区",
      "subArea": []
    }]
  }, {
    "id": 450900,
    "areaName": "玉林市",
    "subArea": [{
      "id": 450981,
      "areaName": "北流市",
      "subArea": []
    }, {
      "id": 450923,
      "areaName": "博白县",
      "subArea": []
    }, {
      "id": 450903,
      "areaName": "福绵区",
      "subArea": []
    }, {
      "id": 450922,
      "areaName": "陆川县",
      "subArea": []
    }, {
      "id": 450982,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 450921,
      "areaName": "容县",
      "subArea": []
    }, {
      "id": 450924,
      "areaName": "兴业县",
      "subArea": []
    }, {
      "id": 450902,
      "areaName": "玉州区",
      "subArea": []
    }]
  }]
}, {
  "id": 810000,
  "areaName": "香港特别行政区",
  "subArea": [{
    "id": 810200,
    "areaName": "九龙",
    "subArea": [{
      "id": 810205,
      "areaName": "观塘区",
      "subArea": []
    }, {
      "id": 810204,
      "areaName": "黄大仙区",
      "subArea": []
    }, {
      "id": 810201,
      "areaName": "九龙城区",
      "subArea": []
    }, {
      "id": 810203,
      "areaName": "深水埗区",
      "subArea": []
    }, {
      "id": 810202,
      "areaName": "油尖旺区",
      "subArea": []
    }]
  }, {
    "id": 810100,
    "areaName": "香港岛",
    "subArea": [{
      "id": 810103,
      "areaName": "东区",
      "subArea": []
    }, {
      "id": 810104,
      "areaName": "南区",
      "subArea": []
    }, {
      "id": 810102,
      "areaName": "湾仔",
      "subArea": []
    }, {
      "id": 810101,
      "areaName": "中西区",
      "subArea": []
    }]
  }, {
    "id": 810300,
    "areaName": "新界",
    "subArea": [{
      "id": 810301,
      "areaName": "北区",
      "subArea": []
    }, {
      "id": 810302,
      "areaName": "大埔区",
      "subArea": []
    }, {
      "id": 810308,
      "areaName": "葵青区",
      "subArea": []
    }, {
      "id": 810309,
      "areaName": "离岛区",
      "subArea": []
    }, {
      "id": 810307,
      "areaName": "荃湾区",
      "subArea": []
    }, {
      "id": 810303,
      "areaName": "沙田区",
      "subArea": []
    }, {
      "id": 810306,
      "areaName": "屯门区",
      "subArea": []
    }, {
      "id": 810304,
      "areaName": "西贡区",
      "subArea": []
    }, {
      "id": 810305,
      "areaName": "元朗区",
      "subArea": []
    }]
  }]
}, {
  "id": 330000,
  "areaName": "浙江省",
  "subArea": [{
    "id": 330100,
    "areaName": "杭州市",
    "subArea": [{
      "id": 330108,
      "areaName": "滨江区",
      "subArea": []
    }, {
      "id": 330127,
      "areaName": "淳安县",
      "subArea": []
    }, {
      "id": 330183,
      "areaName": "富阳区",
      "subArea": []
    }, {
      "id": 330105,
      "areaName": "拱墅区",
      "subArea": []
    }, {
      "id": 330182,
      "areaName": "建德市",
      "subArea": []
    }, {
      "id": 330104,
      "areaName": "江干区",
      "subArea": []
    }, {
      "id": 330185,
      "areaName": "临安市",
      "subArea": []
    }, {
      "id": 330186,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 330102,
      "areaName": "上城区",
      "subArea": []
    }, {
      "id": 330122,
      "areaName": "桐庐县",
      "subArea": []
    }, {
      "id": 330106,
      "areaName": "西湖区",
      "subArea": []
    }, {
      "id": 330103,
      "areaName": "下城区",
      "subArea": []
    }, {
      "id": 330109,
      "areaName": "萧山区",
      "subArea": []
    }, {
      "id": 330110,
      "areaName": "余杭区",
      "subArea": []
    }]
  }, {
    "id": 330500,
    "areaName": "湖州市",
    "subArea": [{
      "id": 330523,
      "areaName": "安吉县",
      "subArea": []
    }, {
      "id": 330522,
      "areaName": "长兴县",
      "subArea": []
    }, {
      "id": 330521,
      "areaName": "德清县",
      "subArea": []
    }, {
      "id": 330503,
      "areaName": "南浔区",
      "subArea": []
    }, {
      "id": 330524,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 330502,
      "areaName": "吴兴区",
      "subArea": []
    }]
  }, {
    "id": 330400,
    "areaName": "嘉兴市",
    "subArea": [{
      "id": 330481,
      "areaName": "海宁市",
      "subArea": []
    }, {
      "id": 330424,
      "areaName": "海盐县",
      "subArea": []
    }, {
      "id": 330421,
      "areaName": "嘉善县",
      "subArea": []
    }, {
      "id": 330402,
      "areaName": "南湖区",
      "subArea": []
    }, {
      "id": 330482,
      "areaName": "平湖市",
      "subArea": []
    }, {
      "id": 330484,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 330483,
      "areaName": "桐乡市",
      "subArea": []
    }, {
      "id": 330411,
      "areaName": "秀洲区",
      "subArea": []
    }]
  }, {
    "id": 330700,
    "areaName": "金华市",
    "subArea": [{
      "id": 330783,
      "areaName": "东阳市",
      "subArea": []
    }, {
      "id": 330703,
      "areaName": "金东区",
      "subArea": []
    }, {
      "id": 330781,
      "areaName": "兰溪市",
      "subArea": []
    }, {
      "id": 330727,
      "areaName": "磐安县",
      "subArea": []
    }, {
      "id": 330726,
      "areaName": "浦江县",
      "subArea": []
    }, {
      "id": 330785,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 330702,
      "areaName": "婺城区",
      "subArea": []
    }, {
      "id": 330723,
      "areaName": "武义县",
      "subArea": []
    }, {
      "id": 330782,
      "areaName": "义乌市",
      "subArea": []
    }, {
      "id": 330784,
      "areaName": "永康市",
      "subArea": []
    }]
  }, {
    "id": 331100,
    "areaName": "丽水市",
    "subArea": [{
      "id": 331122,
      "areaName": "缙云县",
      "subArea": []
    }, {
      "id": 331127,
      "areaName": "景宁畲族自治县",
      "subArea": []
    }, {
      "id": 331102,
      "areaName": "莲都区",
      "subArea": []
    }, {
      "id": 331181,
      "areaName": "龙泉市",
      "subArea": []
    }, {
      "id": 331182,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 331121,
      "areaName": "青田县",
      "subArea": []
    }, {
      "id": 331126,
      "areaName": "庆元县",
      "subArea": []
    }, {
      "id": 331124,
      "areaName": "松阳县",
      "subArea": []
    }, {
      "id": 331123,
      "areaName": "遂昌县",
      "subArea": []
    }, {
      "id": 331125,
      "areaName": "云和县",
      "subArea": []
    }]
  }, {
    "id": 330200,
    "areaName": "宁波市",
    "subArea": [{
      "id": 330206,
      "areaName": "北仑区",
      "subArea": []
    }, {
      "id": 330282,
      "areaName": "慈溪市",
      "subArea": []
    }, {
      "id": 330283,
      "areaName": "奉化市",
      "subArea": []
    }, {
      "id": 330203,
      "areaName": "海曙区",
      "subArea": []
    }, {
      "id": 330205,
      "areaName": "江北区",
      "subArea": []
    }, {
      "id": 330204,
      "areaName": "江东区",
      "subArea": []
    }, {
      "id": 330226,
      "areaName": "宁海县",
      "subArea": []
    }, {
      "id": 330284,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 330225,
      "areaName": "象山县",
      "subArea": []
    }, {
      "id": 330212,
      "areaName": "鄞州区",
      "subArea": []
    }, {
      "id": 330281,
      "areaName": "余姚市",
      "subArea": []
    }, {
      "id": 330211,
      "areaName": "镇海区",
      "subArea": []
    }]
  }, {
    "id": 330800,
    "areaName": "衢州市",
    "subArea": [{
      "id": 330822,
      "areaName": "常山县",
      "subArea": []
    }, {
      "id": 330881,
      "areaName": "江山市",
      "subArea": []
    }, {
      "id": 330824,
      "areaName": "开化县",
      "subArea": []
    }, {
      "id": 330802,
      "areaName": "柯城区",
      "subArea": []
    }, {
      "id": 330825,
      "areaName": "龙游县",
      "subArea": []
    }, {
      "id": 330882,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 330803,
      "areaName": "衢江区",
      "subArea": []
    }]
  }, {
    "id": 330600,
    "areaName": "绍兴市",
    "subArea": [{
      "id": 330621,
      "areaName": "柯桥区",
      "subArea": []
    }, {
      "id": 330684,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 330682,
      "areaName": "上虞区",
      "subArea": []
    }, {
      "id": 330683,
      "areaName": "嵊州市",
      "subArea": []
    }, {
      "id": 330624,
      "areaName": "新昌县",
      "subArea": []
    }, {
      "id": 330602,
      "areaName": "越城区",
      "subArea": []
    }, {
      "id": 330681,
      "areaName": "诸暨市",
      "subArea": []
    }]
  }, {
    "id": 331000,
    "areaName": "台州市",
    "subArea": [{
      "id": 331003,
      "areaName": "黄岩区",
      "subArea": []
    }, {
      "id": 331002,
      "areaName": "椒江区",
      "subArea": []
    }, {
      "id": 331082,
      "areaName": "临海市",
      "subArea": []
    }, {
      "id": 331004,
      "areaName": "路桥区",
      "subArea": []
    }, {
      "id": 331083,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 331022,
      "areaName": "三门县",
      "subArea": []
    }, {
      "id": 331023,
      "areaName": "天台县",
      "subArea": []
    }, {
      "id": 331081,
      "areaName": "温岭市",
      "subArea": []
    }, {
      "id": 331024,
      "areaName": "仙居县",
      "subArea": []
    }, {
      "id": 331021,
      "areaName": "玉环县",
      "subArea": []
    }]
  }, {
    "id": 330300,
    "areaName": "温州市",
    "subArea": [{
      "id": 330327,
      "areaName": "苍南县",
      "subArea": []
    }, {
      "id": 330322,
      "areaName": "洞头县",
      "subArea": []
    }, {
      "id": 330303,
      "areaName": "龙湾区",
      "subArea": []
    }, {
      "id": 330302,
      "areaName": "鹿城区",
      "subArea": []
    }, {
      "id": 330304,
      "areaName": "瓯海区",
      "subArea": []
    }, {
      "id": 330326,
      "areaName": "平阳县",
      "subArea": []
    }, {
      "id": 330383,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 330381,
      "areaName": "瑞安市",
      "subArea": []
    }, {
      "id": 330329,
      "areaName": "泰顺县",
      "subArea": []
    }, {
      "id": 330328,
      "areaName": "文成县",
      "subArea": []
    }, {
      "id": 330324,
      "areaName": "永嘉县",
      "subArea": []
    }, {
      "id": 330382,
      "areaName": "乐清市",
      "subArea": []
    }]
  }, {
    "id": 330900,
    "areaName": "舟山市",
    "subArea": [{
      "id": 330921,
      "areaName": "岱山县",
      "subArea": []
    }, {
      "id": 330902,
      "areaName": "定海区",
      "subArea": []
    }, {
      "id": 330903,
      "areaName": "普陀区",
      "subArea": []
    }, {
      "id": 330923,
      "areaName": "其它区",
      "subArea": []
    }, {
      "id": 330922,
      "areaName": "嵊泗县",
      "subArea": []
    }]
  }]
}];